name: Continuous Integration
on: push
env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: Root@123
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{env.DB_USER}}"@"localhost" IDENTIFIED BY "${{env.DB_PASSWORD}}";'
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}} -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}'
      - name: Checkout Repo Clone
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run Tests
        run: go test