name: Continuous Integration
on: push
env:
  DB_NAME: test
  DB_USER: root
  DB_PASSWORD: password
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          apt-get install -y mysql-client
          mysql --host mydb -uroot -ppassword -e "SHOW DATABASES"
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}} -u${{env.DB_USER}} -p${{env.DB_PASSWORD}};' -uroot -proot
      - name: Checkout Repo Clone
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run Tests
        run: go test